version: '3' 

services:
  app:
    container_name: react-sample-app-101
    image: node:17-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'